# Example player class. Stats arent final, format may change

[Main]
name = "Knight"
hitbox_size = 6
skills = [ "Slash" ]

[Stats]
hp = 100
dmg = 10
mov_spd = 3

[Assets]
sprite = "player"
#TODO: add some sound that will be played on getting hit
#hurt_sound =
death_sound = "player_death"

[Animations.idle_right]
sprites = [ 0, 0 ]
loop = true

[Animations.idle_left]
sprites = [ 4, 4 ]
loop = true

[Animations.move_right]
sprites = [ 8, 11 ]
loop = true

[Animations.move_left]
sprites = [ 12, 15 ]
loop = true

[Animations.attack_right]
sprites = [ 16, 19 ]
loop = true

[Animations.attack_left]
sprites = [ 20, 23 ]
loop = true

[Animations.hurt_right]
sprites = [ 24, 27 ]

[Animations.hurt_left]
sprites = [ 28, 31 ]

[Animations.dying_left]
sprites = [ 32, 35 ]

[Animations.dying_right]
sprites = [ 36, 39 ]
