# Example player class. Stats arent final, format may change

[Main]
name = "Knight"
hitbox_size = 6
skills = [ "Slash" ]

[Stats]
hp = 100
dmg = 10
# Basic defence, that reduce any direct damage received to (dmg - defence) but
# never below 1
defence = 5
mov_spd = 3

[Assets]
sprite = "player"
#TODO: add some sound that will be played on getting hit
#hurt_sound =
death_sound = "player_death"

[Animations.idle]
sprites = [ 0, 0 ]
loop = true

[Animations.move]
sprites = [ 4, 7 ]
loop = true

[Animations.attack]
sprites = [ 8, 11 ]
loop = true

[Animations.hurt]
sprites = [ 12, 15 ]

[Animations.dying]
sprites = [ 16, 19 ]
