[Main]
name = "Ranger"
hitbox_size = 6
skills = [ "Shoot" ]
#skills = [ "Plant Mine" ]

[Stats]
hp = 100
dmg = 10
mov_spd = 4
defence = 0
dodge = 10

[Assets]
sprite = "ranger"
death_sound = "player_death"

[Animations.idle]
sprites = [ 0, 0 ]
loop = true

[Animations.move]
sprites = [ 4, 7 ]
loop = true

[Animations.attack]
sprites = [ 8, 11 ]
loop = true

[Animations.dying]
sprites = [ 12, 15 ]
