#!/usr/bin/env python3

#game launcher script

import logging
import Game

log = logging.getLogger()
log.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter(fmt='[%(asctime)s][%(name)s][%(levelname)s] %(message)s', datefmt='%H:%M:%S'))
log.addHandler(handler)

play = Game.game_window.Main()
log.info("Running the game")
play.run()
