[Main]
name = "Autoattack"

caster_animation = "attack"

projectile = "Invisible"
#projectile_scale = 1.5
projectilile_hitbox = 16
projectile_lifetime = 0.1
knockback = 0
cast_time = 0.1
cooldown = 0.1

[Stats]
dmg = 0
dmg_multiplier = 1

[Effects.caster]
stun = 0.1
