[Main]
name = "Autoattack"
caster_animation = "attack"
cast_time = 0.1
cooldown = 0.1

[Projectile]
name = "Invisible"
#scale = 1.5
hitbox = 16
lifetime = 0.1
knockback = 0

[Stats]
dmg = 0
dmg_multiplier = 1

[Effects.caster]
stun = 0.1
