[Main]
name = "Shoot"
caster_animation = "attack"
#caster_animation_speed = 1
cast_time = 0.4
cooldown = 0.4

[Projectile]
name = "Bullet"
spawn_offset = 16
lifetime = 0.3
# Projectile knockback. Knocks target furter from caster on collision with projectile
# Its optional too and I was tempting to put it onto stats, but for now that it
knockback = 0
# Optional variable that sets up projectile speed. Only used if projectile's
# behavior is set to "follow_target" or "move_towards_direction" - otherwise
# either based on caster's movement speed or 0
speed = 6
die_on_collision = true
behavior = "move_towards_direction"

[Stats]
# Skill's damage
dmg = 0
# Damage multiplier
dmg_multiplier = 0.5
