name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Linux x86_64", os: ubuntu-latest, python-version: "3.8", target-platform: "manylinux2010_x86_64" }
          - { name: "Windows x86_64", os: windows-latest, python-version: "3.8", target-platform: "win_amd64" }

    name: ${{ matrix.config.name }} python ${{ matrix.config.python-version }}
    runs-on: ${{ matrix.config.os }}

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup Python ${{ matrix.config.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python-version }}

    - name: Setup Environment
      run: |
        # Update pip
        python -m pip install -U pip setuptools wheel

        # Install dependencies
        pip install -r requirements.txt

    - name: Build
      run: |
        python setup.py build_apps --build-base ./build --platforms ${{ matrix.config.target-platform }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.name }}
        path: build/${{ matrix.config.target-platform }}/
        if-no-files-found: error
