name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.target-platform }} python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        arch: [x86_64]
        python-version: ["3.8"]
        target-platform: ["manylinux2010_x86_64", "win_amd64"]

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Environment
      run: |
        # Update pip
        python -m pip install -U pip setuptools wheel

        # Install dependencies
        pip install -r requirements.txt

    - name: Build
      run: |
        python setup.py build_apps --build-base ./build --platforms ${{ matrix.target-platform }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target-platform }}
        path: build/${{ matrix.target-platform }}/
        if-no-files-found: error
